name: 'Deploy to Neocities'
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy to Neocities'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: eritbh/neocities-upload@master
        with:
          neocities_token: ${{ secrets.NEOCITIES_API_KEY }}
          directory: '.'
